question_data = [

    {
        "category": "Entertainment: Japanese Anime & Manga",
        "type": "boolean",
        "difficulty": "easy",
        "question": "In the 1988 film &quot;Akira&quot;, Tetsuo ends up destroying Tokyo.",
        "correct_answer": "True",
        "incorrect_answers": ["False"]},
    {
        "category": "Geography",
        "type": "boolean",
        "difficulty": "easy",
        "question": "A group of islands is called an &#039;archipelago&#039;.",
        "correct_answer": "True",
        "incorrect_answers": ["False"]},
    {
        "category": "Geography",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Vatican City is a country.",
        "correct_answer": "True",
        "incorrect_answers": ["False"]},
    {
        "category": "Politics",
        "type": "boolean",
        "difficulty": "easy",
        "question": "There was a satirical candidate named &quot;Deez Nuts&quot; running in the 2016 US presidential elections.",
        "correct_answer": "True",
        "incorrect_answers": ["False"]},
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Bulls are attracted to the color red.",
        "correct_answer": "False",
        "incorrect_answers": ["True"]},
    {
        "category": "Science: Gadgets",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The communication protocol NFC stands for Near-Field Control.",
        "correct_answer": "False",
        "incorrect_answers": ["True"]},
    {
        "category": "Entertainment: Board Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The card game &quot;Munchkin&quot; won the 2001 Origins Award for Best Traditional Card Game.",
        "correct_answer": "True",
        "incorrect_answers": ["False"]},
    {
        "category": "Vehicles",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The full English name of the car manufacturer BMW is Bavarian Motor Works",
        "correct_answer": "True",
        "incorrect_answers": ["False"]},
    {
        "category": "Entertainment: Film",
        "type": "boolean",
        "difficulty": "easy",
        "question": "In the movie The Revenant, DiCaprio&#039;s character hunts down the killer of his son.",
        "correct_answer": "True",
        "incorrect_answers": ["False"]},
    {
        "category": "Politics",
        "type": "boolean",
        "difficulty": "easy",
        "question": "One of Barack Obama&#039;s United States presidential campaign slogan&#039;s was &quot;Yes We Can&quot;.",
        "correct_answer": "True",
        "incorrect_answers": ["False"]},
    {
        "category": "Animals",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Cats have whiskers under their legs.",
        "correct_answer": "True",
        "incorrect_answers": ["False"]},
    {
        "category": "Geography",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Hungary is the only country in the world beginning with H.",
        "correct_answer": "False",
        "incorrect_answers": ["True"]},
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Several characters in &quot;Super Mario 64&quot; blink their eyes, including Mario himself.",
        "correct_answer": "True",
        "incorrect_answers": ["False"]},
    {
        "category": "Geography",
        "type": "boolean",
        "difficulty": "easy",
        "question": "New Haven is the capital city of the state of Connecticut in the United States.",
        "correct_answer": "False",
        "incorrect_answers": ["True"]},
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "In the &quot;S.T.A.L.K.E.R.&quot; series, the Freedom faction wishes to destroy the supernatural area known as  &quot;the Zone&quot;.",
        "correct_answer": "False",
        "incorrect_answers": ["True"]},
    {
        "category": "Vehicles",
        "type": "boolean",
        "difficulty": "easy",
        "question": "BMW M GmbH is a subsidiary of BMW AG that focuses on car performance.",
        "correct_answer": "True",
        "incorrect_answers": ["False"]},
    {
        "category": "Entertainment: Television",
        "type": "boolean",
        "difficulty": "easy",
        "question": "&quot;The Simpsons&quot; family is named after creator Matt Groening&#039;s real family.",
        "correct_answer": "True",
        "incorrect_answers": ["False"]},
    {
        "category": "Sports",
        "type": "boolean",
        "difficulty": "easy",
        "question": "There are a total of 20 races in Formula One 2016 season.",
        "correct_answer": "False",
        "incorrect_answers": ["True"]},
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Codemasters is the developer of the Gran Turismo series.",
        "correct_answer": "False",
        "incorrect_answers": ["True"]},
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The mitochondria is the powerhouse of the cell.",
        "correct_answer": "True",
        "incorrect_answers": ["False"]}
]
